native/package-lock.json, native/store/index.js, package-lock.json, package.json
---
Added components folder/index.js, store folder/index.js, and index.js for native folder. Installed native-base as a dependency.
=> project structure

package-lock.json
=> Update package-lock.json for hoek

native/root-stack.js
---
fix root-stack merge conflict
=> root-stack-fix

native/components/frequency-selector.js
slider submit button console.logs an array of task objects
=> closes #21

native/components/home.js, native/components/select-tasks.js, native/components/task-card.js
- Created Select-Tasks component to see sorted list of all tasks
- Created task-card component to use in above component
=> Select tasks

native/components/select-tasks.js
user can now add a task to be selected, when the list is submitted it console logs an array of the task objects.
=> closes #31

native/App.js, native/components/login.js, native/package-lock.json, native/package.json, native/store/auth.js, native/store/index.js, package-lock.json
=> User login wire up #32

native/components/home.js, native/components/login.js, native/package-lock.json, native/package.json, native/store/auth.js, native/store/index.js, script/seed.js, server/auth/index.js, server/db/models/user.js, server/index.js
=> login and seed working

native/components/scores.js, native/package-lock.json, native/store/community.js, native/store/index.js, native/store/users.js, server/api/communities.js, server/api/index.js, server/api/users.js, server/db/models/index.js
---
Gets user scores from the database.
=> Scores full

native/components/player-detail-edit.js, native/components/player-detail.js, native/components/scores.js
---
player detail from database
=> player detail from database

native/components/frequency-selector.js, native/components/select-tasks.js, native/store/auth.js, native/store/index.js, native/store/suggested-tasks.js, server/api/community-tasks.js, server/db/models/task-item.js
see commit messages
also renamed taskList in redux store to be more appropriately named suggestedTasks
=> closes #47

native/store/suggested-tasks.js, server/api/community-tasks.js
changing frequency of a task no longer changes existing task items
=> closes #49

native/components/home.js
=> menu in nav bar

native/components/player-detail-edit.js, native/components/player-detail.js, native/store/auth.js, server/api/users.js
---
played details can be edited
=> player-details-edit

native/store/community-tasks.js, server/api/communities.js, server/api/community-tasks.js
=> closes #74

native/components/task-card.js, native/components/task-list.js, native/drawer-navigation.js, native/package-lock.json, package-lock.json
style changes on task-list/task-card
=> style task list closes #87

native/components/create-community.js, native/components/login.js, server/db/models/user.js
emails to lowercase, styling changes
=> closes #96

native/components/task-list.js
---
pull down to refresh tasks list
=> pull to refresh

native/components/frequency-selector.js, native/components/invite.js, native/components/login.js, native/components/player-detail-edit.js, native/components/player-detail.js, native/components/select-tasks.js, native/components/stats.js, server/auth/paypal.js
=> Stats scores

native/components/select-tasks.js, native/components/task-list.js, native/store/community-tasks.js, native/store/suggested-tasks.js, package-lock.json, script/seed.js, server/api/communities/task-items.js, server/api/communities/tasks.js, server/api/community-tasks.js, server/api/tasks.js, server/db/models/community-task.js, server/db/models/task.js
=> closes #111

native/components/player-detail.js, native/components/scores.js, native/store/index.js, native/store/scores.js, server/api/communities/communities.js, server/api/users.js, server/db/models/user.js
=> Monthly scores

native/components/select-tasks.js, package-lock.json
=> merge-conflict

native/components/player-detail.js, native/components/scores.js, native/store/index.js, native/store/past-winners.js, script/seed.js
=> past-winners

native/components/invite.js, native/components/player-detail-edit.js, native/components/player-detail.js
=> player style

native/components/scores.js
anytime she wanna dip im providing the sauce
=> style scores

native/components/index.js, native/components/past-task-card.js, native/components/past-tasks.js, native/drawer-navigation.js, script/seed.js
=> past-tasks

native/components/stats.js
=> chart animation

native/components/stats.js, server/api/users.js
=> Scoring stats

native/components/select-task-item.js, native/components/select-tasks.js, native/package-lock.json, package-lock.json
bunch of styling in select-tasks
=> closes #167

native/components/index.js, native/components/scores.js, native/components/task-list.js
=> closes #166

server/api/push.js
=> no push notifications without token

native/components/loading-screen.js
=> loading screen

native/components/select-task-item.js, native/components/select-tasks.js
=> closes #196

server/api/task-items.js, server/api/task-items.spec.js, server/api/tasks.spec.js, server/db/models/community-task.js
all tests verified and passing
=> all tests passing and verified

server/api/task-items.js, server/api/task-items.spec.js
bug in task item test fixed, console log deleted
=> closes #216

.babelrc, package.json, server/api/task-items.js, server/api/users.spec.js, server/db/models/task-item.js, server/db/models/task-item.spec.js, server/db/models/user.spec.js
=> TaskItem model tests

native/components/select-tasks.js
added a done button on select-tasks
=> closes #209

native/components/stats.js
=> fixed label

native/components/stats.js
=> changes to structure

server/db/models/task-item.spec.js
=> tests fixed

native/components/camera.js, native/components/custom-header.js, native/components/invite.js, native/components/loading-screen.js, native/components/login.js, native/components/no-community.js, native/components/player-detail-edit.js, native/components/select-tasks.js, native/components/signup.js, native/components/stats.js, native/components/task-list.js, native/components/welcome.js
I went through each component and deleted all of the modules that were imported but never used
=> removed unused imports
